language: python

# this list can be easily generated py running `tox -l`
env:
    - TOX_ENV=py27-django14
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110

# Currently, Python 3.5 Interpreter is only available when it is specified
# in the travis python section. So we have to work around this with this include
# GitHub issue: https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
  - python: "3.5"
    env:
      - TOX_ENV=py35-django18
  - python: "3.5"
    env:
      - TOX_ENV=py35-django19
  - python: "3.5"
    env:
      - TOX_ENV=py35-django110

install:
    - pip install tox
    - pip install coveralls

script:
    - tox -e $TOX_ENV

sudo: false

after_success:
    coveralls
