language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO=django==1.4.*
    - DJANGO=django==1.6.*
    - DJANGO=django==1.7.*
    - DJANGO=django==1.8.*

sudo: false

install:
    - pip install -r requirements-test.txt
    - pip install $DJANGO
    - pip install coveralls

script:
    coverage run runtests.py

after_success:
    coveralls

matrix:
    allow_failures:
        - env: DJANGO=django==1.4.*
        - env: DJANGO=django==1.6.*
    fast_finish: true
